<?php
/**
* Display all the table node in page
*/

/**
* Implements hook_menu()
*/
function show_table_menu(){
    $items['show_table'] = array(
        'type' => MENU_NORMAL_ITEM,
        'title' => t('Show table'),
        'page callback' => 'show_table_content',
        'file' => 'show_table.pages.inc',
        'file path' => drupal_get_path('module', 'show_table'),
        'access arguments' => array('access trong content')
    );
    
    $items['admin/config/content/show_table'] = array(
        'type' => MENU_NORMAL_ITEM,
        'title' => t('Show table'),
        'description' => 'Customs show table',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('options_table_form'),
        'file' => 'show_table.pages.inc',
        'file path' => drupal_get_path('module', 'show_table'),
        'access arguments' => array('access trong content')
    );
    
    return $items;
}
















